### ISSUE TITLE
Update to latest version of tslint?

### ISSUE THREAD

**Issue by karfau** [bcherny/tslint-no-circular-imports#1]
Any plans to maintain this project?
Running it with current version (5.4.3) a warning is logged about 

`Warning: Cannot read property 'resolvedFileName' of undefined`

I guess https://github.com/bcherny/tslint-no-circular-imports/blob/master/noCircularImportsRule.ts#L34 doesn't work anymore?

Also there are a lot of APIs that are used in the rule being marked as deprecated...

I might be able to support this endeavor.

Best Christian

**Comment by bcherny** [comment]
@karfau PRs are welcome! If PR looks good, I'm more than happy to add you as a contributor.

**Comment by bcherny** [comment]
@karfau I just published v0.2.0 to NPM.  Try it out!
