### ISSUE TITLE
Consider to add some changelog (enhancement)

### ISSUE THREAD

**Issue by joseluisq** [bcherny/tslint-no-circular-imports#16]
Hi @bcherny,
I'm a happy user of your package!
Well, I don't want to seem intrusive but It would be awesome if you could support some `changelog.md` to see your fixes and improvements more easily.
Other good option could be [GitHub Releases](https://github.com/bcherny/tslint-no-circular-imports/releases)

What do you think?

**Comment by bcherny** [comment]
Hey Jose! I’m happy to add one. FYI, the changes shouldn’t affect you besides improving the quality of lint suggestions.
