### ISSUE TITLE
Tests always fail on Windows

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [bcherny/tslint-no-circular-imports#24]
After running `npm run test` or just `node test/test.js`:

```
AssertionError [ERR_ASSERTION]: [ { failure:
     'circular import detected: case1.ts -> case1.2.ts -> case1.ts',
    name: 'D:/Code/tslint-no-circular-impor... deepEqual [ { failure:
     'circular import detected: case1.ts -> case1.2.ts -> case1.ts',
    name: 'D:\\Code\\tslint-no-circular-imp...
    at child_process_1.exec (D:\Code\tslint-no-circular-imports\test\test.js:17:12)
    at ChildProcess.exithandler (child_process.js:298:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

#13 would fix this nicely. @geanpeixoto if you don't have the time to come back to this, would you like me to open a new PR with merge conflicts resolved and place some sample output in it too?

**Comment by bcherny** [comment]
@JoshuaKGoldberg What exactly is the bug here? Did you dig into it?

**Comment by JoshuaKGoldberg** [comment]
It looks like the problem is directory slashes being different: in one line of output above they're forward, in another they're backward.

**Comment by bcherny** [comment]
It's hard for me to debug without being on Windows, but could it be related to hard coded path separators in test cases? Eg. https://github.com/bcherny/tslint-no-circular-imports/blob/8c7e2984aa67d80d6e2069b7d68d2a3c05504d63/test/test.ts#L31

**Comment by chigix** [comment]
I've fixed tests problems on windows: https://github.com/bcherny/tslint-no-circular-imports/pull/29

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues - TSLint is deprecated :)
