### ISSUE TITLE
Running tslint . is deprecated

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [bcherny/tslint-no-circular-imports#25]
```
> tslint-no-circular-imports@0.5.0 lint D:\Code\tslint-no-circular-imports
> tslint .

'.' does not exist. This will be an error in TSLint 6.
```

Things move so fast these days...

Edit: I started working on a quick PR then realized there's no `tslint.json` checked in here. Is that intentional?

**Comment by bcherny** [comment]
> Edit: I started working on a quick PR then realized there's no tslint.json checked in here. Is that intentional?

Embarrassing oversight :)
