### ISSUE TITLE
Various problems running within in Visual Studio

### ISSUE THREAD

**Issue by andyrooger** [bcherny/tslint-no-circular-imports#4]
I'm using this in Visual Studio with `tslint-language-service`. There are a number of problems we've had.

* ~VS 2017 latest seems to come bundled with node v5.4.1, which doesn't appear support all the syntax in the ES2015 build (#6)~
* ~The rules work the first time the linter is run, but any errors remain even after they're fixed. The only way to stop them is to reopen the project (#10 )~
* ~The tests in this repo don't work on Windows (#5)~
* ~The typings for node get dragged in when we install the package, and cause conflicts in our main project. I suspect they should be a dev dependency? (#7 , #8 )~

We have fixed these locally, so I'm happy to PR them - do you prefer separate PRs for the separate issues or all together?

**Comment by bcherny** [comment]
That would be awesome, and separate PRs would be ideal. This repo is unfortunately pretty out of date.

**Comment by andyrooger** [comment]
Thanks @bcherny . The first two changes are PRed - I can put a PR in for the typings after #6 so it doesn't conflict. The sticky errors problem is taking longer that I expected to try and be sure I've fixed it properly, rather than just for me.

I noticed [this branch](https://github.com/bcherny/tslint-no-circular-imports/tree/revert-5-4-tests-on-windows) pop up. Should I be worried I've broken things?

**Comment by bcherny** [comment]
> I noticed this branch pop up. Should I be worried I've broken things?

Nope, accidentally clicked Revert because Github was being slow :) Please carry on.

**Comment by andyrooger** [comment]
Looks like all the PRs for this issue are in now. @bcherny Should I be closing this now or when they are in a release?

**Comment by bcherny** [comment]
Published 0.3.0. Thanks for all the contributions @andyrooger!!!

**Comment by bcherny** [comment]
Ping me next time you're in San Francisco and I'll buy you a beer. 🍻

**Comment by andyrooger** [comment]
Fantastic! Thanks for putting them in! And I'll hold you to that :)
