### ISSUE TITLE
Set to warning state?

### ISSUE THREAD

**Issue by ajmas** [bcherny/tslint-no-circular-imports#40]
Not seeing in the docs how to make this simply display as a warning, rather than an error?

**Comment by bcherny** [comment]
Do either of these work for you? https://stackoverflow.com/questions/46517832/how-to-extend-airbnb-eslint-but-with-warnings-instead-of-errors

**Comment by ajmas** [comment]
Well, only if I knew the rule name. Is it 'no-circular-imports'?

**Comment by bcherny** [comment]
Right! You can see that in https://github.com/bcherny/tslint-no-circular-imports/blob/master/tslint-no-circular-imports.json#L4

If you think this will be useful for others and want to put up a PR adding it to README.md, I’ll be happy to approve it.
